export const TRAITS = [
  "stubborn",
  "insular",
  "iconoclast",
  "conformist",
  "defector",
  "bandwagoner",
  "martyr",
  "doubter",
  "diplomat",
  "heretic",
  "zealot",
  "forceful",
  "charismatic",
  "contrarian",
  "hippie",
  "rationalist",
  "spinner",
  "passionate",
  "avenger",
  "insurgent",
  "polarizer",
] as const;

export const SELECTABLE_TRAITS = [
  "stubborn",
  "insular",
  "iconoclast",
  "conformist",
  "defector",
  "bandwagoner",
  "martyr",
  "doubter",
  "diplomat",
  "heretic",
  "forceful",
  "charismatic",
  "contrarian",
  "hippie",
  "rationalist",
  "spinner",
  "passionate",
  "avenger",
  "insurgent",
  "polarizer",
] as const;
