"""Shared default timers for Among Us mission variants."""

from amongcogs.constants import (
    COMMS_SABOTAGE_TIMER_STEPS,
    INITIAL_KILL_COOLDOWN_STEPS,
    INITIAL_SABOTAGE_COOLDOWN_STEPS,
    KILL_COOLDOWN_STEPS,
    LIGHTS_SABOTAGE_TIMER_STEPS,
    MEETING_DURATION_STEPS,
    OXYGEN_SABOTAGE_TIMER_STEPS,
    REACTOR_SABOTAGE_TIMER_STEPS,
    SABOTAGE_COOLDOWN_STEPS,
    VENT_COOLDOWN_STEPS,
)

DEFAULT_KILL_COOLDOWN_STEPS = KILL_COOLDOWN_STEPS
DEFAULT_INITIAL_KILL_COOLDOWN_STEPS = INITIAL_KILL_COOLDOWN_STEPS
DEFAULT_INITIAL_SABOTAGE_COOLDOWN_STEPS = INITIAL_SABOTAGE_COOLDOWN_STEPS
DEFAULT_MEETING_DURATION_STEPS = MEETING_DURATION_STEPS
DEFAULT_REACTOR_SABOTAGE_TIMER_STEPS = REACTOR_SABOTAGE_TIMER_STEPS
DEFAULT_OXYGEN_SABOTAGE_TIMER_STEPS = OXYGEN_SABOTAGE_TIMER_STEPS
DEFAULT_LIGHTS_SABOTAGE_TIMER_STEPS = LIGHTS_SABOTAGE_TIMER_STEPS
DEFAULT_COMMS_SABOTAGE_TIMER_STEPS = COMMS_SABOTAGE_TIMER_STEPS
DEFAULT_SABOTAGE_COOLDOWN_STEPS = SABOTAGE_COOLDOWN_STEPS
DEFAULT_VENT_COOLDOWN_STEPS = VENT_COOLDOWN_STEPS
