"""Shared default settings for Werewolf/Mafia mission variants."""

DEFAULT_MAX_STEPS = 500
DEFAULT_NIGHT_STEPS = 20
DEFAULT_DAY_STEPS = 30
DEFAULT_FULL_VISION_RADIUS = 6
DEFAULT_BLIND_VISION_RADIUS = 0
DEFAULT_EXECUTION_THRESHOLD = 2
DEFAULT_NIGHT_KILLS_PER_PHASE = 1
DEFAULT_TALK_MAX_LENGTH = 140
DEFAULT_TALK_COOLDOWN_STEPS = 6
